[0m06:45:35.612526 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f624d7edc70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f624dd04bf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f624d9292e0>]}


============================== 06:45:35.624309 | 9e0fd665-3c30-4c2c-a6af-8c66f40d2da9 ==============================
[0m06:45:35.624309 [info ] [MainThread]: Running with dbt=1.10.11
[0m06:45:35.627081 [debug] [MainThread]: running dbt with arguments {'use_colors': 'True', 'debug': 'False', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'indirect_selection': 'eager', 'invocation_command': 'dbt init demo_dcs_dbtmodel_v1', 'partial_parse': 'True', 'introspect': 'True', 'warn_error': 'None', 'write_json': 'True', 'log_cache_events': 'False', 'target_path': 'None', 'version_check': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'quiet': 'False', 'empty': 'None', 'printer_width': '80', 'cache_selected_only': 'False', 'profiles_dir': '/home/spark-8c73f9f5-1f2b-4f69-b080-1f/.dbt', 'fail_fast': 'False', 'use_experimental_parser': 'False', 'static_parser': 'True', 'log_path': 'logs', 'log_format': 'default'}
[0m06:45:35.658165 [info ] [MainThread]: Creating dbt configuration folder at /home/spark-8c73f9f5-1f2b-4f69-b080-1f/.dbt
[0m06:45:35.692330 [debug] [MainThread]: Starter project path: /local_disk0/.ephemeral_nfs/envs/pythonEnv-8c73f9f5-1f2b-4f69-b080-1feec0136a85/lib/python3.12/site-packages/dbt/include/starter_project
[0m06:45:37.641243 [info ] [MainThread]: 
Your new dbt project "demo_dcs_dbtmodel_v1" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m06:45:37.644830 [info ] [MainThread]: Setting up your profile.
[0m06:45:37.649264 [error] [MainThread]: Encountered an error:

[0m06:45:37.653423 [error] [MainThread]: Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8c73f9f5-1f2b-4f69-b080-1feec0136a85/lib/python3.12/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8c73f9f5-1f2b-4f69-b080-1feec0136a85/lib/python3.12/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8c73f9f5-1f2b-4f69-b080-1feec0136a85/lib/python3.12/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8c73f9f5-1f2b-4f69-b080-1feec0136a85/lib/python3.12/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8c73f9f5-1f2b-4f69-b080-1feec0136a85/lib/python3.12/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8c73f9f5-1f2b-4f69-b080-1feec0136a85/lib/python3.12/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m06:45:37.657129 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 2.312922, "process_in_blocks": "48", "process_kernel_time": 0.128472, "process_mem_max_rss": "103308", "process_out_blocks": "0", "process_user_time": 1.999359}
[0m06:45:37.661079 [debug] [MainThread]: Command `dbt init` failed at 06:45:37.660788 after 2.32 seconds
[0m06:45:37.665115 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f624cd1f680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f624dd04bf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f624d759df0>]}
[0m06:45:37.668334 [debug] [MainThread]: Flushing usage events
[0m06:45:38.557149 [debug] [MainThread]: An error was encountered while trying to flush usage events
